version: '3.8'

services:
  api:
    build: ./api_server
    ports:
      - "8000:8000"
    depends_on:
      - ml
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - ML_API_URL=http://ml:5000

  ml:
    build: ./ml_matcher
    ports:
      - "5000:5000"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
