version: '3.8'

services:
  api:
    build: ./api_server
    ports:
      - "8000:8000"
    depends_on:
      - ml
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - ML_API_URL=http://ml:5000
    volumes:
      - ./api_server:/app
    restart: unless-stopped

  ml:
    build: ./ml_matcher
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./ml_matcher:/app
    restart: unless-stopped

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  mongo_data: